### ISSUE TITLE
[NEW]: Web3privacy now meetup

### ISSUE THREAD

**Issue by Msiusko** [blockchainweek/data#1]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Web3privacy now meetup"

# shortest possible name (without year)
shortname = "W3PN"

# type of the event
types = ["meetup"]

# status of the event
status = "planning"

# the name of the group organizing the event
org = "Web3Privacy now"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "https://github.com/burningtree"

# A point of contact (responsible person)
poc = "https://matrix.to/#/#web3privacy:matrix.org"

# the start date of the event
date = "2024-05-22"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-21:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["c-base]

# the event venue name
venueName = "c base"

# link to the venue on google maps
venueUrl = "https://maps.app.goo.gl/pXMTtejEaSUNno2HA"

# the event venue address
venueAddress = "Rungestraße 20, 10179 Berlin, Germany"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 300

# blockchains that the event deals with
# if it is an interchain event, then leave blank

# tags for the event, will show up as labels.
# pick 1-4
tags = ["lunarpunk", "privacy", "censorship resistance", "cypherphunk"]

# A logo attachment
logo = "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,quality=75,width=400,height=400/event-covers/pq/73637b17-538e-44fa-a75a-5da505ba9d47"

# a description of the event.
description = "Web3Privacy now community presents core meetup of the privacy enthusiasts @ ETHBerlin 4. Explore the latest privacy market insights, presentations from the key privacy protocols & dApps, talk through regulatory pressure & anti-censorship efforts behind privacy community players""

[registration]
type = "signup"

# price of the ticket
price = "TBD EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/w3pn-meetup-berlin1"

# custom action button label
#button = "Register!"

# status of registrations
status = "available"

[links]
web = "https://lu.ma/w3pn-meetup-berlin1"
web = "http://web3privacy.info"

# twitter account
twitter = "https://twitter.com/web3privacy"

# public telegram group
telegram = "https://t.me/web3privacynow"
```
