### ISSUE TITLE
[NEW]: ZKProof.org 6th Standardization Workshop

### ISSUE THREAD

**Issue by jonmrjr** [blockchainweek/data#101]
```toml
# the name of your event
name = "ZKProof.org 6th Standardization Workshop"

# shortest possible name (without year)
shortname = "ZKProof 6"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["conference"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "ZKProof.org"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "@jonrouach"

# A point of contact (responsible person)
poc = "Jonathan Rouach"

# the start date of the event
date = "2024-05-22"

# how many days the event lasts (1 - N)
days = 3

# the event times (shows up in the event card)
times = "09:00-18:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "Hilton Doubletree Ku'damm"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/way/26412513"

# the event venue address
venueAddress = "Los-Angeles-Platz 1, 10789 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 130

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = []

# tags for the event, will show up as labels.
# pick 1-4
tags = ["cryptography", "zkp", "zk", "zero-knowledge-proof"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
ZKProof is an initiative focused on the standardization of Zero-Knowledge Proofs. This community of over 1000 practitioners converges stakeholders from academia, startups, and law enforcement, creating a bridge between theory and practical implementation.
"""

[cfp]
# link to call for particioation
link = "https://zkproof.org/events/zkproof-6-berlin/"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "595 USD"

# link to the registration or ticket purchase page
link = "https://zkproof.org/events/zkproof-6-berlin/"

# custom action button label
#button = "Buy tickets!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://zkproof.org/events/zkproof-6-berlin/"

# twitter account
twitter = "https://x.com/zkproof"

```
