### ISSUE TITLE
[NEW]: Longevity Meetup Berlin

### ISSUE THREAD

**Issue by laurenceion** [blockchainweek/data#102]
```toml
# the name of your event
name = "Longevity Meet-up Berlin 2024"

# shortest possible name (without year)
shortname = "Longevity Meetup"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "VitaDAO"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "john007"

# A point of contact (responsible person)
poc = "Laurence Ion"

# the start date of the event
date = "2024-05-24"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "18:00-20:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "DeSci church"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/search.html?q=Alexandrienstra%C3%9Fe+18+10969+Berlin"

# the event venue address
venueAddress = "Alexandrinenstraße 118-121, 10969 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 50

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["network states", "longevity"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """

Join us for a casual meetup of revolutionaries against aging & death during Berlin Blockchain Week.

​Longevity x Don't Die x DeSci


"""

[cfp]
# link to call for particioation
link = "https://lu.ma/longevity-berlin"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/longevity-berlin"

# custom action button label
#button = "sign up!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/longevity-berlin"

# twitter account
# twitter = "https://twitter.com/ExampleConf"

# public matrix channel
# matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
# telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
# discord = "https://discord.com/invite/AsDf1337"
```
