### ISSUE TITLE
STREAMM.XYZ : FARCASTER VIDEO CLIENT - LAUNCH PARTY 🎉

### ISSUE THREAD

**Issue by UNITECHIL** [blockchainweek/data#104]
```toml
# the name of your event
name = "Discover Streamm.xyz: The Future of Livestreams and Videocasts with Farcaster Integration"

# shortest possible name (without year)
shortname = "Streamm.xyz"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "planning"

# the name of the group organizing the event
org = "Streamm.xyz"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "UNITECHIL"

# A point of contact (responsible person)
poc = "https://warpcast.com/streamm"

# the start date of the event
date = "2024-05-20"

# how many days the event lasts (1 - N)
days = 8

# the event times (shows up in the event card)
times = "09:00-20:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["Mindspace Friedrichstraße"]

# the event venue name
venueName = "Mindspace Friedrichstraße"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/node/535088858#map=19/52.51242/13.38975"

# the event venue address
venueAddress = "Friedrichstraße 68, 10117 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 50

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "base"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["socialfi", "cryptography"]

# A logo attachment
logo = "(https://i.ibb.co/kgLgS6J/3-1.png)"

# a description of the event.
description = """
Join us during Berlin Blockchain Week for an exclusive introduction to Streamm.xyz, a groundbreaking new video client designed for the Web3 community. Streamm.xyz offers:

- Livestreams and Videocasts: Engage with real-time and recorded content tailored for the blockchain ecosystem.
- Creator Keys for Gated Content: Empower creators with tools to control access and monetize their content.
- Full @farcaster Integration: Seamless interaction with the Farcaster protocol, including responses, likes, and follows.

This event is perfect for content creators, developers, and blockchain enthusiasts looking to explore innovative ways to connect and engage with their audience. Don't miss the opportunity to be part of the future of video content in Web3!
"""

[cfp]
# link to call for participation
link = "https://streamm.xyz"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://streamm.xyz"

# custom action button label
#button = "Register"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://streamm.xyz

# twitter account
twitter = "https://twitter.com/streamm_xyz"
```
