### ISSUE TITLE
[NEW]: New Event: "Showroom: Bitcoin Real World Products"

### ISSUE THREAD

**Issue by BitcoinBeginnerWorkshops** [blockchainweek/data#109]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Showroom: Bitcoin Real World Products"

# shortest possible name (without year)
shortname = "Bitcoin Showroom"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["expo"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Bitcoin Lab Berlin"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "BitcoinBeginnerWorkshops"

# A point of contact (responsible person)
poc = "BitcoinBeginnerWorkshops"

# the start date of the event
date = "2024-05-25"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00-18:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
venues = ["web3hub"]

# # the event venue name
# venueName = "w3.hub"

# # link to the venue on google maps
# venueUrl = "https://maps.app.goo.gl/UhWpUeuFDtJ3BTQw6"

# # the event venue address
# venueAddress = "Möckernstraße 120, 10963 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english", "german"]

# the max number of attendees of the event
attendees = 2121

# blockchains that the event deals with
# if it is an interchain event, then leave blank
# chains = ["Bitcoin"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Bitcoin", "BitcoinOnly", "StudyBitcoin", "ThereIsNoSecondBest"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
**You really thought Bitcoin is boring? Let us proof you wrong!**

We have what 'other chains' lack: real life applications! We show you:
- Bitcoin sauna via Bitcoin mining (self-build)
- Bitcoin fruit drying via Bitcoin mining (bitcoin-mango.com)
- Bitcoin heater via Bitcoin mining (21energy.com)
- Send Bitcoin on your own phone in 1 second (Lightning Network Self-Experience)
- See where you can already pay with Bitcoin in Berlin (btcmap.org)
- IOT: Pay a jukebox, beer tap and other machines in Bitcoin
- Ordimint: NFT the Bitcoin way
- Bitcoin Full-Node Set-Up for your home
- Smallest Bitcoin Miner: Nerdminer
- 'Bitcoin im Bundestag': An ongoing initiative to inform about Bitcoin in the German Parliament

If you are new to Bitcoin, we can talk about why we think it is the future of money. Get in touch with us!

**Sign-In:**
Not required - show up as you wish. Free admission!

**How To Find:**
We will be on the 2. floor in the community kitchen.
"""

# [cfp]
# # link to call for particioation
# link = "https://www.meetup.com/bitcoin-lab-berlin/events/301056693"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://www.meetup.com/bitcoin-lab-berlin/events/301056693"

# custom action button label
#button = "Free Entry!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://www.meetup.com/bitcoin-lab-berlin/events/301056693"

# twitter account
#twitter = "https://twitter.com/chainlink"

# public matrix channel
#matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
#telegram = "https://t.me/chainlinkofficial"

# docs
#docs = "https://docs.chain.link/"

# discord
#discord = "https://discord.com/invite/chainlink"
```
