### ISSUE TITLE
[NEW]: Builder Nights changes date

### ISSUE THREAD

**Issue by andreolf** [blockchainweek/data#113]
Please use this template to suggest a new event location or update an existing one for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/places) to this repository. This will speed up things significantly!

```toml
# name of the venue
name = "Builder nights https://blockchainweek.berlin/24/event/buildernight need to be changed to Friday, and not Saturday anymore"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
eventTypes = ["conference", "hackathon"]

# max number of attendees
capacity = 350

# Street address
address = "Lohmuehlenstraße 65, 12435 Berlin"

# OSM Maps URL
mapUrl = "https://nominatim.openstreetmap.org/ui/search.html?q=Rungestra%C3%9Fe+20+10179+Berlin"

# Venue Description
description = '''
Example Venue is an ecosystem of over 3,500 members from more than 70 nations located on two campuses – Fantasy Park and Utopia Mitte.
'''

# Venue Photo or Logo
photo = "logo.png"

# Venue Link
[links]
web = "https://example.com/spaces/"
```
