### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by Ayse-Merve** [blockchainweek/data#119]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Tech Open Air"

# shortest possible name (without year)
short name = "TOA"

# type of the event:
#   * meetup
#   * conference
#   * startup pitch competition
#   * expo
#   * party


# Status of the event
status = "published"

# The name of the group organizing the event
org = "Tech Open Air"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "Ayse-Merve"

# A point of contact (responsible person)
poc = "Ayse-Merve"

# the start date of the event
date = "2024-06-04 / 2024-06-07"

# how many days the event lasts (1 - N)
days = 4

# the event times (shows up in the event card)
times = "09:00-20:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["colosseum-kino"]

# the event venue name
venueName = "Colosseum Kino"

# link to the venue on open-street maps
venueUrl = "https://www.google.com/maps?hl=de&gl=de&um=1&ie=UTF-8&fb=1&sa=X&ftid=0x47a853e0d0b7c9eb:0x9c00fe8d2915980a"

# the event venue address
venueAddress = "Schönhauser Allee 123, 10437 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 4000

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "polkadot"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["solarpunk", "cryptography"]
![Linkedin](https://github.com/blockchainweek/data/assets/79096500/5cd5c487-947c-46cd-a716-916215d44b7b)


# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
🚀 TOA celebrates a decade of Frontier Technology as Berlin’s Tech & Startup Event. Join TOA this year for capital, talent, customers, and inspiration from June 4-7.  Attendees from 30+ countries will enjoy events like the TOA Conference and Satellite Events, Open Circle, and a Closing Party.  Explore areas like AI, Climate Tech, Web3, Health Tech, and Business Success.

Here is 3 reasons why you should attend TOA24: 

🚀 Engage with Visionaries: Dive into a four-day event journey with the brightest minds in tech, discussing future trends that might seem like fiction today but will become tomorrow's reality.

💡 Forge Valuable Connections: Meet with founders, investors, top talent, and potential customers. Each interaction holds the potential to spark new growth avenues for your company.

🌟 Be Part of an Influential Community: Join a dynamic network of pioneers across frontier technologies, all converging to share insights and push the envelope in their respective fields.

Learn More <https://event.toa.media/program>
Get your TO24 Community Tickets <https://ti.to/tech-open-air-berlin/toa24/discount/SWiTU24DevTOA24>
"""

[cfp]
# link to call for participation
link = "https://event.toa.media/speakers"

[registration]
# type of registration
type = "tickets and scholarships (free tickets upon admission and acreditation)"

# price of the ticket
price = " various depending on ticket type"

# link to the registration or ticket purchase page
scholarship link = "https://toaberlin.typeform.com/to/ZT0hxEcF"
ticket link = "https://ti.to/tech-open-air-berlin/toa24?source=marketing-campaigns"

# custom action button label
#button = "Apply for Scholarships!"
#button = "Get your TOA24 tickets!"


# status of registrations
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://event.toa.media/"

# twitter account
twitter = "https://x.com/TOABerlin"


```
