### ISSUE TITLE
[NEW]: w3.hub

### ISSUE THREAD

**Issue by hbredi** [blockchainweek/data#13]
Please use this template to suggest a new event location or update an existing one for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/places) to this repository. This will speed up things significantly!

```toml
# name of the venue
name = "w3.hub"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
eventTypes = ["conference", "hackathon, meetup, expo"]

# max number of attendees
capacity = 200

# Street address
address = "Möckernstraße 120, 10963 Berlin"

# OSM/Google Maps URL
mapUrl = "https://maps.app.goo.gl/GG6E7PYJ3dXSnmgr9"

# Venue Description
description = '''
w3.hub is Berlin's Home of Web3. Work, Connect & Celebrate Web3 at w3.hub.
'''

# Venue Photo or Logo
photo = "
![w3 hub :: transparent](https://github.com/blockchainweek/data/assets/61271324/85f433d3-5335-411e-afed-514988f0fbf8)
"

# Venue Link
[links]
web = "https://w3hub.berlin/host-events"
```
