### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by SantaBerlin** [blockchainweek/data#17]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "First in the World Web3 Drone Corridor Launch"

# shortest possible name (without year)
shortname = "Web3 Drone Launch"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = "Launch"

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "Scheduled Launch"

# the name of the group organizing the event
org = "Staex"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "@SantaBerlin"

# A point of contact (responsible person)
poc = "Paksy Plackis-Cheng"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-16:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = "Im Marienpark, Berlin, https://marienpark.berlin/"

# the event venue name
venueName = "Im Marienpark"

# link to the venue on google maps
venueUrl = "https://maps.app.goo.gl/GsFcvSkFPcQ1hH669"

# the event venue address
venueAddress = "Im Marienpark, 12107 Berlin-Bezirk Tempelhof-Schöneberg"

# the languages in which the event will take place (you can choose more)
languages = "English, German"

# the max number of attendees of the event
attendees = "100"

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = "Lisk"

# tags for the event, will show up as labels.
# pick 1-4
tags = "machine-to-machine, machine payments, Web2 co using Web3 tools, drones"

# A logo attachment
logo = "
![Rewe Group paymenttools](https://github.com/blockchainweek/data/assets/163290027/df584830-8d9e-43a3-b8ea-db637d883981)
![Vantage Towers ](https://github.com/blockchainweek/data/assets/163290027/190db084-10b3-4cc1-9dcc-224d394beae5)
![Germandrones](https://github.com/blockchainweek/data/assets/163290027/5daf0ab6-54af-47af-a396-42e0451ed8d6)
![staex-logo](https://github.com/blockchainweek/data/assets/163290027/0895127e-18c0-4b12-8829-c8a79d2ab241)
![Untitled](https://github.com/blockchainweek/data/assets/163290027/9b70bfb5-b0d5-43ce-ad16-399d988b5d2d)"

# a description of the event.
description = """
Invitation to the official Web3 Drone Corridor launch in Berlin
An Actual Industry Usage of Web3 Tools

Join us for the World’s First Web3 Drone Corridor launch on May 21st, 2024. Don't miss out on German best-of-breed technologies featuring reliable and secure data capturing, communication, and processing incl. payment. Secure your spot and be an active participant purchasing your photo (data) realtime that will be captured by a drone utilizing machine-to-machine payments.

Here's what to expect:

When: May 21st, 2024, at 15:00.
If you are press or a Staex partner, your event starts at 14:00.
Where: [Im Marienpark, 12107 Berlin](https://maps.app.goo.gl/GsFcvSkFPcQ1hH669).
"""

[cfp]
# link to call for particioation
link = "https://staex.io/web3-drone-corridor"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "public part is FREE!"

# link to the registration or ticket purchase page
link = "https://staex.io/web3-drone-corridor-announcement"

# custom action button label
#button = "Register now!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://staex.io/web3-drone-corridor-announcement"

# twitter account
twitter = "https://twitter.com/staex_io"

# public matrix channel
matrix = ""

# public telegram group
telegram = ""

# docs
#docs = ""

# discord
discord = ""
```
