### ISSUE TITLE
Blockchain meets AI + BerChain’s 5th Anniversary

### ISSUE THREAD

**Issue by sndpbjri** [blockchainweek/data#20]
```toml
# the name of your event
name = "Blockchain meets AI + BerChain’s 5th Anniversary"

# shortest possible name (without year)
shortname = "Blockchain meets AI"

# type of the event
types = ["conference"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "BerChain"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "sndpbjri"

# A point of contact (responsible person)
poc = "Marta Dal Lago"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "14:00-22:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["[w3hub Berlin](https://maps.app.goo.gl/YQNp6fqTLxXcs4YW8)"]

# the event venue name
venueName = "w3.hub"

# link to the venue on google maps
venueUrl = "https://maps.app.goo.gl/YQNp6fqTLxXcs4YW8"

# the event venue address
venueAddress = "Möckernstraße 120, 10963 Berlin, Germany"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 150

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [""]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["blockchain", "artificialintelligence", "usecase", "ai"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """Explore the current state of AI and its connections with blockchain and web3 technologies! Join a vivid cross tech communities event and a panel of thrilling speakers! Use cases and applications, the differences of the international landscapes, the issues posed by AI and the relationship between players/technology with policy makers and regulations will be discussed.
The event will be prolonged with the 5th anniversary part of BerChain. Celebrate with Berlin’s biggest blockchain and web3 community, meet old and new friends, looking back at five inspiring years, and looking ahead to more blockchain futures together! """

[cfp]
# link to call for participation
link = "https://www.eventbrite.co.uk/e/blockchain-meets-ai-berchains-5th-anniversary-tickets-880861940777?aff=BBW2024"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://www.eventbrite.co.uk/e/blockchain-meets-ai-berchains-5th-anniversary-tickets-880861940777?aff=BBW2024"

# custom action button label
#button = "Buy tickets!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://www.eventbrite.co.uk/e/blockchain-meets-ai-berchains-5th-anniversary-tickets-880861940777?aff=BBW2024"

# twitter account
twitter = "https://twitter.com/Berchain"

```
