### ISSUE TITLE
[NEW] ZK Hack Kraków (May 17-19)

### ISSUE THREAD

**Issue by guelowrd** [blockchainweek/data#23]
```toml
# the name of your event
name = "ZK Hack Kraków, an IRL zk-focused hackathon"

# shortest possible name (without year)
shortname = "ZK Hack Kraków"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["hackathon"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "ZK Hack"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "guelowrd"

# A point of contact (responsible person)
poc = "Gaylord Warner"

# the start date of the event
date = "2024-05-17"

# how many days the event lasts (1 - N)
days = 3

# the event times (shows up in the event card)
times = "00:00-24:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "CKF13 Centrum Konferencyjne Fabryczna 13, Kraków"

# link to the venue on google maps
venueUrl = "https://maps.app.goo.gl/vFfxUQYQ4biRJ4w76"

# the event venue address
venueAddress = "Fabryczna 13, 31-553 Kraków, Poland"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 300

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["aleph zero", "mina", "polygon", "scroll", "ethereum"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["zero-knowledge", "cryptography", "hackathon"]

# A logo attachment
logo = "Zk Kraków black.png"
![Zk Kraków black](https://github.com/blockchainweek/data/assets/102294720/3c43f1fe-723d-47bf-b9d3-a0eefc794514)

# a description of the event.
description = """
From May 17th to 19th,  we host ZK Hack Kraków, ZK Hack's third IRL zk-hackathon.

At ZK Hack Kraków, we will be hacking on zk-tools, using zk-DSLs, and building new products that showcase what zk can do. Hackers and builders will get to meet the teams working on zk, learn new skills, find collaborators and friends as well as imagine new ways to use zk in real world applications.
"""

[cfp]
# link to call for particioation
link = "https://www.zkkrakow.com/"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "invites"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://zk-hack-krakow.devfolio.co/"

# custom action button label
#button = "Apply to hack!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://www.zkkrakow.com/"

# twitter account
twitter = "https://twitter.com/__zkhack__"

# public matrix channel
matrix = ""

# public telegram group
telegram = "https://t.me/+TORo7aknkYNLHmCM"

# docs
#docs = ""

# discord
discord = "https://discord.gg/xzAdSSsbrf"
```
