### ISSUE TITLE
[NEW]: Starknet Foundation Meetup- Berlin Blockchain Week Edition

### ISSUE THREAD

**Issue by teamgurkha** [blockchainweek/data#29]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Starknet Foundation Meetup- Berlin Blockchain Week Edition
"

# shortest possible name (without year)
shortname = "Starknet Foundation Meetup- Berlin"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Starknet Foundation"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "teamgurkha"

# A point of contact (responsible person)
poc = "Gurk & Amy"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "17:30 - 19:30"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "Atelier Rooftop"

# link to the venue on google maps
venueUrl = "https://www.google.com/maps/search/ api=1&query=Atelier%20Rooftop&query_place_id=ChIJF3UEMixOqEcR5C8SS0jK-o0"

# the event venue address
venueAddress = "Prinzenstraße 84.1, 10969 Berlin, Germany"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees =150

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["Ethereum", "Starknet"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["STARKS", "ZK", "L3"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
Lorem ipsum ...
"""

[cfp]
# link to call for participation
link = "https://lu.ma/k8xdqbkt"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/k8xdqbkt"

# custom action button label
#button = "Get tickets!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/k8xdqbkt"

# twitter account
twitter = "https://twitter.com/starknetevents"

# public matrix channel
matrix = " "

# public telegram group
telegram = " "

# docs
#docs = "https://book.starknet.io/"

# discord
discord = "https://discord.gg/K4BwQVbm"
```
