### ISSUE TITLE
[NEW]: CHAINFLIP HAPPY HOUR

### ISSUE THREAD

**Issue by Willywhoot** [blockchainweek/data#45]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Chainflip Happy Hour"

# shortest possible name (without year)
shortname = "Chainflip Happy Hour"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Chainflip Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "Willywhoot"

# A point of contact (responsible person)
poc = "William Johs"

# the start date of the event
date = "2024-05-24"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-19:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["Schlesische Strasse, 20"]

# the event venue name
venueName = "Studio 20"

# link to the venue on open-street maps
venueUrl = "https://www.google.com/maps/place/Schlesische+Str.+20,+10997+Berlin/@52.4984854,13.4436294,17z/data=!3m1!4b1!4m6!3m5!1s0x47a84e53b257101f:0xc2cc6a6a3e0a3771!8m2!3d52.4984854!4d13.4462043!16s%2Fg%2F11bw3ybm_0?entry=ttu"

# the event venue address
venueAddress = "Schlesische Strasse 20, 10179 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 300

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "bitcoin", "arbitrum", "solana", "polkadot"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["HappyHour", "Cross-chain"]

# A logo attachment
logo = "![photo_2024-04-30 14 24 49](https://github.com/blockchainweek/data/assets/168553834/11dd2a3d-2580-46d0-8dfa-e9974c88d4f2)"

# a description of the event.
description = """
​Come join us for a Happy Hour in Berlin with tunes, beers, cocktails, and food. Alongside the Chainflip crew, we'll have Crypto Builders, Developers, and the wider Web3 Community joining us. So, yeah, networking.

​Here's what you can expect:

- ​Local Berlin Beers
​- Homemade Cocktails 
- ​Our very own CEO on the decks 
- ​Meet the Chainflip team and fellow Berlin Builders
​- Get your hands on some of our Merch
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/32mmm5em"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "Free"

# link to the registration or ticket purchase page
link = "https://lu.ma/32mmm5em"

# custom action button label
#button = "Sign up here!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/32mmm5em"

# twitter account
twitter = "https://twitter.com/Chainflip"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/chainflip_io_chat"

# docs
#docs = "https://docs.chainflip.io/concepts/thesis-and-introduction"

# discord
discord = "https://discord.com/invite/chainflip-community"
```
