### ISSUE TITLE
[NEW]: Rooftop Token Launch Party with Drinks and Pizza by Welshare Health

### ISSUE THREAD

**Issue by jockschulz** [blockchainweek/data#46]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Rooftop Token Launch Party with Drinks and Pizza by Welshare Health"

# shortest possible name (without year)
shortname = "Welshare Rooftop Night"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Welshare Health"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "jockschulz"

# A point of contact (responsible person)
poc = "Jock Schulz"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "19:00-22:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = [Welshare HQ, https://www.google.com/maps/place/Voltairestra%C3%9Fe+11,+10179+Berlin,+Germany/@52.5177284,13.4164585,16z/data=!3m1!4b1!4m6!3m5!1s0x47a84e2256eb8309:0xc3e64aa57cff055c!8m2!3d52.5177284!4d13.4164585!16s%2Fg%2F11j2vvq0f4?entry=ttu, Voltairestr 11"]

# the event venue name
venueName = "Welshare Health HQ"

# link to the venue on google maps
venueUrl = "https://www.google.com/maps/place/Voltairestra%C3%9Fe+11,+10179+Berlin,+Germany/@52.5177284,13.4164585,16z/data=!3m1!4b1!4m6!3m5!1s0x47a84e2256eb8309:0xc3e64aa57cff055c!8m2!3d52.5177284!4d13.4164585!16s%2Fg%2F11j2vvq0f4?entry=ttu"

# the event venue address
venueAddress = "Voltairestr 11, 10179 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 269

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = []

# tags for the event, will show up as labels.
# pick 1-4
tags = ["desci", "health", "token"]

# A logo attachment
logo = "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=1,quality=75,width=400,height=400/event-covers/ox/a69cbdfa-3388-4cc2-965e-b07f62def8b0"

# a description of the event.
description = "Let's enjoy the sunset of Berlin together after the first day of DappCon!

Cold Drinks and delicious Pizza provided throughout the night.

Welshare Health is disrupting the digital health landscape with the power of DeSci. Our web3 app enables you to personalize your contribution to medical research.

Own your health data, contribute to medical research without the need of a middleman, earn rewards based on the true value of your health data and benefit from personalized health.

We have exciting guests lined up from Digital Health, Medical AI, Pharma, DeSci and of course leaders from patient communities which we are co-creating with.

This is a first of a kind event where we bring together leaders from web2 and web3 to discuss the innovative future of healthcare.

To celebrate this endeavor, we soon will be launching the Welshare token and opening the public presale. Don't miss out on the opportunity to get on the exclusive token waitlist!

https://twitter.com/welsharehealth"


[cfp]
# link to call for particioation
link = "https://lu.ma/welshare.health"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "FREE"

# link to the registration or ticket purchase page
link = "https://lu.ma/welshare.health"

# custom action button label
#button = "Sign up here!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/welshare.health"

# twitter account
twitter = "https://twitter.com/welsharehealth"

# public matrix channel
matrix = ""

# public telegram group
telegram = "https://t.me/welsharehealth"

# docs
#docs = ""

# discord
discord = ""
```
