### ISSUE TITLE
[NEW]: ChainSafe & Friends: Berlin (event)

### ISSUE THREAD

**Issue by BenAdarSafe** [blockchainweek/data#47]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = ChainSafe & Friends: Berlin

# shortest possible name (without year)
shortname = ChainSafe & Friends

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = meetup

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = planning

# the name of the group organizing the event
org = ChainSafe

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = BenAdarSafe

# A point of contact (responsible person)
poc = Ben Adar

# the start date of the event
date = 2024-05-22

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = 18:00-22:00

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = betahaus | Kreuzberg

# the event venue name
venueName = betahaus | Kreuzberg

# link to the venue on open-street maps
venueUrl = https://www.openstreetmap.org/search?whereami=1&query=52.50659%2C13.39155#map=19/52.50659/13.39155

# the event venue address
venueAddress = Rudi-Dutschke-Straße 23, 10969 Berlin, Germany

# the languages in which the event will take place (you can choose more)
languages = English

# the max number of attendees of the event
attendees = 50

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ethereum, polkadot, and cross-chain solutions

# tags for the event, will show up as labels.
# pick 1-4
tags = Cross-Chain, Account Abstraction

# A logo attachment
logo = ChainSafe.png
![ChainSafe](https://github.com/blockchainweek/data/assets/66450053/43ca9918-465e-46fb-a658-c00d3ec2c7b6)

# a description of the event.
description = 
Join us in Berlin for an intimate gathering for web3 folks hosted by ChainSafe & Sygma

​Discover cutting-edge advancements driving the future of open-source, public goods, and decentralized technology.

​Whether you're an experienced developer, an entrepreneurial visionary, or simply curious about the endless possibilities of web3, this event is for you.

[cfp]
# link to call for particioation
link = 

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = signup

# price of the ticket
price = free

# link to the registration or ticket purchase page
link = https://lu.ma/csconberlin

# custom action button label
#button = "Sign-Up!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = available

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = https://lu.ma/csconberlin

# twitter account
twitter = https://twitter.com/ChainSafeth

# public matrix channel
matrix = 

# public telegram group
telegram = 

# docs
#docs = 

# discord
discord = https://discord.com/invite/xSAwrnCWcg
```
