### ISSUE TITLE
[NEW]: Metabrew Community Meetup

### ISSUE THREAD

**Issue by Aresss** [blockchainweek/data#48]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Metabrew Community organized Meetup"

# shortest possible name (without year)
shortname = "Metabrew"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Metabrew Ambassador"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "Aresss"

# A point of contact (responsible person)
poc = "Werner Hoffmann"

# the start date of the event
date = "2024-05-19"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "19:00-22:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "RedRum Art Bar"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=7340692918&class=amenity"

# the event venue address
venueAddress = "Grimmstraße 24, 10967 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english", "german"]

# the max number of attendees of the event
attendees = 60

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = []

# tags for the event, will show up as labels.
# pick 1-4
tags = ["meetup", "metabrew", "nft", "community", "beer"]

# A logo attachment
logo = ![Metabrew Community Meetup](https://github.com/blockchainweek/data/assets/2854708/e43dfb2c-bf26-4d6d-b012-0546f1490554)

# a description of the event.
description = """
This is a Meetup and pop-up store for Metabrew - the web3 beer as part of the Berlin Blockchain Week. We welcome everyone there is no need to be part of the Metabrew community already.

​MetaBrewSociety is the leading Web3 beer brand and community. Created by a group of friends and entrepreneurs who love crypto, tech, beer, delicious food and festivals.

​No agenda just a casual hangout at a bar drinking beer, talking about crypto, NFTs and realworld applications.

​(This is not a official Metabrew event nor sponsored by it.)

​There will be Metabrew for sell, only hard money accepted (cash, Bitcoin lightning and for easiness Matic).

​

​Looking forward to see many of you there.
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/oa2mv636"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "Free!"

# link to the registration or ticket purchase page
link = "https://lu.ma/oa2mv636"

# custom action button label
#button = "Signup!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/oa2mv636/"

# twitter account
# twitter = "https://twitter.com/ExampleConf"

# public matrix channel
# matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
# telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
# discord = "https://discord.com/invite/AsDf1337"
```
