### ISSUE TITLE
[NEW]: Hack'N Heights: Unlocking Decentralized Data on a Berlin Rooftop

### ISSUE THREAD

**Issue by lorena1974** [blockchainweek/data#49]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Hack'N Heights: Unlocking Decentralized Data on a Berlin Rooftop"

# shortest possible name (without year)
shortname = "Hack'N Heights: Unlocking Decentralized Data on a Berlin Rooftop"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup ¨ ]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published "

# the name of the group organizing the event
org = "Chainlink, The Graph  and Deutsche Telekom¨

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "lorena1974"

# A point of contact (responsible person)
poc = "Lorena Fabris"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "18:00-22:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "Deutsche Telekom building"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/search?query=Winterfeldtstra%C3%9Fe%2021#map=19/52.49633/13.35783"

# the event venue address
venueAddress = "Winterfeldtstraße 21 10781 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 100

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [" "]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["data", "subgraphs", ¨hackathon¨]

# A logo attachment
logo = "![HacknHeights_SocialPost1_C1V3 (2)](https://github.com/blockchainweek/data/assets/71536313/b5267ec3-2bd5-4bd7-9d8e-e126a43838c5)"

# a description of the event.
description = "Set against the dynamic backdrop of a vibrant Berlin rooftop, "Hack'N Heights" invites you to delve into the vast potential of decentralized data during Berlin Blockchain Week 2024. Hosted at the iconic Deutsche Telekom building, this evening with technical presentations serves as the official kick-off for the Hack’N Heights Online Hackathon.Hack’N Heights kickoff event is organized by leading entities including Chainlink, Deutsche Telekom, The Graph Protocol.The virtual hackathon is co-sponsored by Chainlink, The Graph, Plurality Network, Pinax, Deutsche Telekom, and Soonami with Bounties of over 6K and potential investment opportunities for promising projects. We cordially invite you to the vibrating kickoff of Hack’N Heights - A night of enlightenment and connections. Engage with groundbreaking tools and protocols that harness the value of decentralized data through a series of expert-led technical presentations.
Event Highlights:
Expert Presentations: Gain insights from leaders in blockchain technology, including Solange Gueiros from Chainlink Labs, Amaechi Okolobi, a Chainlink Developer Expert and Arturo Castanon Advocate from Graph AdvocatesDAO.
Dynamic Networking: Connect with pioneers and peers within the blockchain and web3 communities. Expand your network, exchange ideas, and discover new opportunities in an inspiring setting.
Complimentary Refreshments: Enjoy a variety of snacks and drinks provided throughout the evening at no cost, ensuring a comfortable and engaging experience.
""
![HacknHeights_SocialPost1_C1V3 (1)](https://github.com/blockchainweek/data/assets/71536313/5a15027a-d997-4908-855c-0b2bb550a689)


[cfp]
# link to call for participation

- link = "https://example.com/speaker"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/66o9s3m8"

# custom action button label
#button = "Join today¨

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://example.org/"

# twitter account
twitter = "https://twitter.com/ExampleConf"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
discord = "https://discord.com/invite/AsDf1337"
```
