### ISSUE TITLE
[NEW]: BBW' 24 Community Run w/ w3.fund

### ISSUE THREAD

**Issue by hbredi** [blockchainweek/data#52]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "BBW' 24 Community Run w/ w3.fund"

# shortest possible name (without year)
shortname = "BBW' 24 Community Run w/ w3.fund"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["other"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "w3.fund"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "hbredi"

# A point of contact (responsible person)
poc = "Henrik Bredenbals"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "07:30-08:30"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["w3.hub"]

# the event venue name
venueName = "w3.hub"

# link to the venue on open-street maps
venueUrl = "https://maps.app.goo.gl/uD1yncPL7ACUYyZs8"

# the event venue address
venueAddress = "Möckernstraße 120, 10963 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 50

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [""]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["fitness", "running", "strongertogether"]

# A logo attachment
logo = "
![blockchain week run](https://github.com/blockchainweek/data/assets/61271324/c673c898-cff0-41b1-8b20-e0269d0129d9)
"


# a description of the event.
description = "Join our run & energize for a lively 5-6km run with fitness stations to test your strength and agility along the way.

​Gear up for an morning of physical challenge and community fun! Register now to secure your spot.

​We will start at 7:30 in front of the w3.hub, please don't be late!

​The run is presented to you by [w3.fund](http://w3.fund/), an early stage Web3 application layer VC fund."


[cfp]
# link to call for particioation
link = "https://example.com/speaker"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/oz82th95"

# custom action button label
#button = "Run with Us :)"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/oz82th95"

# twitter account
twitter = "https://twitter.com/ExampleConf"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
discord = "https://discord.com/invite/AsDf1337"
```
