### ISSUE TITLE
[NEW]: WorkoutDAO

### ISSUE THREAD

**Issue by puncar-dev** [blockchainweek/data#53]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "WorkoutDAO"

# shortest possible name (without year)
shortname = "WorkoutDAO"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "WorkoutDAO"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "puncar-dev"

# A point of contact (responsible person)
poc = "Puncar"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "08:30-10:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["outdoor"]

# the event venue name
venueName = "Outdoor"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/search.html?q=Rungestra%C3%9Fe+20+10179+Berlin"

# the event venue address
venueAddress = "Rungestraße 20, 10179 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 600

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = []

# tags for the event, will show up as labels.
# pick 1-4
tags = ["solarpunk", "workout", "DAO"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
​Lets run through Berlin and enjoy some good networking!
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/zq87qizu"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "free"

# link to the registration or ticket purchase page
link = "https://lu.ma/zq87qizu"

# custom action button label
#button = "Lets Workout!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://workoutdao.com/"

# twitter account
twitter = ""

# public matrix channel
matrix = "workoutdao.com"

# public telegram group
telegram = "https://t.me/+nypYZPQZDDQzOTIx"

# docs
#docs = ""

# discord
discord = ""
```
