### ISSUE TITLE
[NEW]: afk with Lens

### ISSUE THREAD

**Issue by parisrouzati** [blockchainweek/data#54]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "afk Berlin"

# shortest possible name (without year)
shortname = "afk Berlin"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * party
types = ["meetup, conference, party"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Lens Protocol"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "parisrouzati"

# A point of contact (responsible person)
poc = "Paris Rouzati"

# the start date of the event
date = "2024-05-24"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-19:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["Monbijoustr. 11  10117 Berlin"]

# the event venue name
venueName = "Telegraphenamt"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/node/10264516383"

# the event venue address
venueAddress = "Monbijoustr. 11  10117 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 400

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["web3 social", "new internet", "privacy", "scalability"]

# A logo attachment
logo = "[logo.png](https://ik.imagekit.io/lens/media-snapshot/tr:w-1000,q-80/576f955c3a8cbf5c6fd1d9d398c05ee1dce45e8a45ea6ac6deac33d7d6187c51.png)"

# a description of the event.
description = """
AFK is a new event series debuting in Berlin. 
Alongside a line-up of cultural leaders, thinkers and technologists, we invite you to take a break from your laptop, dive into ideas, enjoy great conversations, and enjoy pop-ups from Orb, t2 and Bonsai. We'll wrap the evening up with a set by Sound of Fractures and delicious bites.
"""

[cfp]

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "Free"

# link to the registration or ticket purchase page
link = "https://lu.ma/afkberlin"

# custom action button label
#button = "RSVP on Luma"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/afkberlin"

# twitter account
twitter = "https://twitter.com/lensprotocol"

# docs
#docs = "https://lens.xyz/docs"


```
