### ISSUE TITLE
AFK Berlin

### ISSUE THREAD

**Issue by mariapaulafn** [blockchainweek/data#55]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "AFK"

# shortest possible name (without year)
shortname = "AFK"

types = ["*OTHER"]


status = "*published"


org = "Lens"

dri = "mariapaulafn"


poc = "Cree de Beauvoir"


date = "2024-05-23"

days = 1


times = "16:00-20:00"


# venues = [ "Monbijoustrasse 11, 10117, Berlin"]


venueName = "Telegraphenamt"

venueUrl = "https://www.google.com/maps/search/?api=1&query=Monbijoustra%C3%9Fe%2011&query_place_id=ChIJmUa6aJtRqEcRxzKj8MP0bPQ"

venueAddress = "Monbijoustrasse 11, 10117, Berlin"

languages = ["english"]


attendees = 200

# if it is an interchain event, then leave blank
chains = ["ethereum"]


tags = ["privacy", "scalability", "culture", "decentralized social"]


logo = "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,dpr=2,quality=75,width=400,height=400/event-covers/4w/29164413-9d0b-480c-a5bd-ec04cc4ba30c"


description = """
AFK is a new Lens event series debuting in Berlin. 

​Alongside a line-up of cultural leaders, thinkers and technologists, we invite you to take a break from your laptop, dive into ideas, enjoy great conversations and pop-ups from Orb, t2 and Bonsai. We'll wrap the evening up with a set by Sound of Fractures and delicious bites.
"""

link = "https://lu.ma/afkberlin"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"


price = "0"


link = "https://lu.ma/afkberlin"


#button = "Get tickets!"

status = "available"

[links]

web = "https://lu.ma/afkberlin"

# twitter account
twitter = "https://twitter.com/lensprotocol

```
