### ISSUE TITLE
Berlin Blockchain Week 2024: Governance, subjective rules and RWAs - the frontier of crypto 

### ISSUE THREAD

**Issue by DianaTheKing** [blockchainweek/data#56]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Berlin Blockchain Week 2024: Governance, subjective rules and RWAs - the frontier of crypto"

# shortest possible name (without year)
shortname = "Governance, subjective rules and RWAs - the frontier of crypto"

# type of the event
#  available types (you can choose more):
#   * meetup
types = ["meetup"]

# status of the event
status = "published"

# the name of the group organizing the event
org = "Q Protocol, Kleros"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "DianaTheKing"

# A point of contact (responsible person)
poc = "Diana King"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "17:30-23:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress

# the event venue name
venueName = "Spielfeld Digital Hub"

# link to the venue on open-street maps
venueUrl = "https://maps.app.goo.gl/eV3WyNp1brpBzMmv5"

# the event venue address
venueAddress = "Skalitzer Str. 85/86, 10997 Berlin, Germany"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 200

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "cross-chain"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["governance", "RWA", "web3"]

# A logo attachment
logo = "![luma post-Connecting governance-1 (1)](https://github.com/blockchainweek/data/assets/77386933/91563f92-270f-435b-8a12-a4cdf4f340ae)"

# a description of the event.
description = """
​Q Protocol and Kleros are teaming up to bring you an event that is a deep dive into blockchain governance and the integration of real-world assets. This gathering is your opportunity to connect with fellow enthusiasts and explore a unique blend of expert insights and practical applications.

The agenda will be updated soon.

​Special highlights:

​Meet innovative web3 projects that are pushing the boundaries between web3 and real world assets.

​Network with pioneers, VCs and leaders shaping the future of Web3.

​We can't wait to catch up with all the fellows and dive into the governance sea. Be ready for an evening full of learning, networking, and forward-thinking discussions. See you in Berlin!

​​About Q

​[​Q](https://linktr.ee/qblockchain) is a novel blockchain protocol acting as a fundamental governance layer in Web 3.It combines the benefits of a public, open, and decentralized ledger with the transparency and predictability of enforceable private contracts, thereby enabling adoption by a great variety of use cases that desire decentralization but require scalability and dependability.

​About Kleros

​[Kleros](https://kleros.io/) is a decentralized arbitration platform designed to resolve disputes in a transparent and efficient manner using blockchain technology. It leverages crowdsourced jurors who are incentivized through a token-based system to adjudicate a wide range of cases, from e-commerce disputes to contract disagreements.

About SimplyTokenized

[SimplyTokenized](https://www.simplytokenized.com/) is a platform that enhances financing options for businesses and community engagement. It facilitates easier access to capital through community funding, uses smart contracts for cost and time efficiency, and offers decentralized processing via blockchain. The platform's features aim to increase customer loyalty and community interaction through token-based campaigns and a community portal.

About Closer

[Closer](https://closer.earth/) is platform to enable web3 access to regenerative villages and coliving spaces.

About Crypto Invest Berlin

Join the community at [Crypto Invest Berlin](https://www.cryptoinvest.berlin/), the premier gathering spot for cryptocurrency enthusiasts! Held every third Thursday of the month, these events are designed to foster collaboration and share the collective knowledge that enhances their powerful network.
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/rzrder87"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "free"

# link to the registration or ticket purchase page
link = "https://lu.ma/rzrder87"

# custom action button label
#button = "Join!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/rzrder87"

# twitter account
twitter = "https://twitter.com/qblockchain"

# public telegram group
telegram = "https://t.me/berlin_blockchain_week_agenda"


```
