### ISSUE TITLE
[NEW]: Public-Private Consortium Launch Web3 Drone Corridor

### ISSUE THREAD

**Issue by SantaBerlin** [blockchainweek/data#58]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "First Web3 Drone Corridor in the World"

# shortest possible name (without year)
shortname = "Web3 Drone Corridor"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["launch"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Staex GmbH"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "SantaBerlin"

# A point of contact (responsible person)
poc = "Paksy Plackis-Cheng"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "14:00-17:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["Im Marienpark, Berlin"]

# the event venue name
venueName = "Alter Wasserturm im Marienpark"

# link to the venue on open-street maps
venueUrl = "https://www.google.com/maps/place/Alter+Wasserturm/@52.4385916,13.3700328,18z/data=!4m6!3m5!1s0x47a8454a883fdf53:0x6d270301c5c667c0!8m2!3d52.4392342!4d13.3702731!16s%2Fg%2F11c30xx_f3?entry=tts"

# the event venue address
venueAddress = "Im Marienpark, Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 100+

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "Lisk"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["drones", "Web3", "German tech", "M2M"]

# A logo attachment
logo = "![Staex Web3 Drone Corridor Launch Berlin May 21 2024](https://github.com/blockchainweek/data/assets/163290027/84f45817-0698-413f-8c0d-73ef5468511e)"


# a description of the event.
description = """
An actual industry usage of Web3 tools...A public-private partnership realizing the next in assets sharing, data collection, permit- and contract handling, and machine payments. All of this will be automated with Staex for reliability and security allowing partners across sectors and industries to work with one another. With the use of Web3 tools, we have neutral grounds, built-in trust, smart-contracts, verified immutable data, and machine-to-machine payments.

We are ready to show you a glimpse of the future. Join us for the best-of-breed German technology.

Meet the future-forward Staex partners:
Vantage Towers AG, owner of 84,000+ telco towers across Europe;
REWE Group's paymenttools responsible for 50,000+ payment terminals across Europe; 
Lightcurve, Lisk platform for L2 of Ethereum;
Germandrones GmbH, high-performance drones for surveillance and reconnaissance globally; 
Investa for Im Marienpark, and
Berlin Partner für Wirtschaft und Technologie GmbH representing the Berlin State ecosystem and innovation.

Dr. Severin Fischer, Staatssekretär in der Senatsverwaltung für Wirtschaft, Energie und Betriebe des Landes Berlin will open up the event. 

"""


[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "FREE, please register"

# link to the registration or ticket purchase page
link = "https://www.eventbrite.de/e/official-web3-drone-corridor-launch-in-berlin-tickets-877818236977?aff=oddtdtcreator"

# custom action button label
#button = "Get your ticket today!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://staex.io/web3-drone-corridor-announcement"

# twitter account
twitter = "https://twitter.com/staex_io"

# public matrix channel
matrix = ""

# public telegram group
telegram = ""

# docs
#docs = ""

# discord
discord = ""
```
