### ISSUE TITLE
Hack'n Heights

### ISSUE THREAD

**Issue by lorena1974** [blockchainweek/data#60]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = ¨Hack'n Heights Hybrid Hackathon"

# shortest possible name (without year)
shortname = "Hack'n Heights"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["hackathon" ¨meetup¨ ¨workshop¨ ¨other¨]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Foundance, Soonami, Chainlink, The Graph, Pinax, Plurality Network"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "lorena1974"

# A point of contact (responsible person)
poc = "Lorena Fabris¨

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 7

# the event times (shows up in the event card)
times = "00:00-24:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "Deutsche Telekom "

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/search?query=Winterfeldtstra%C3%9Fe%2021#map=19/52.49633/13.35783"
 

# the event venue address
venueAddress = "Winterfeldtstraße 21 10781 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 600

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [" "]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["subgraph", "substreams"]

# A logo attachment
logo = "![HackinHeights_Logo-500px](https://github.com/blockchainweek/data/assets/71536313/68fd9c17-602c-4b4c-86d4-c1998c1aec2c)"

# a description of the event.
description = " The Hack'N Heights Hybrid Hackathon is dedicated to showcasing how decentralized data can redefine our digital interactions. Our mission is to foster an environment where our bounty sponsors' combined technologies and frameworks—Chainlink, The Graph Protocol, Plurality Network, soonami.io and Pinax—illustrate the compelling advantages of web3 approaches.
The kick-off event will take place on May 21th at Deutsche Telekom Building with technical presentations. We anticipate developers will create exciting applications and explore blockchain technology's next wave of billion-dollar data-related use cases. Chainlink provides decentralized oracles, seamlessly integrating off-chain data into the blockchain world. Similarly, The Graph Protocol efficiently indexes and queries blockchain data, making it accessible for dApps and the broader off-chain landscape. Additionally, Plurality Network offers an onboarding solution, aggregating variable user data from social platforms that can be leveraged for both on-chain and off-chain use cases. We believe developers can craft amazing applications at this intersection of data and blockchain, eagerly look forward to the innovations to come!

This event seeks to illuminate the cohesive power of these technologies, demonstrating their compatibility and strength in solving complex data problems.

What to Expect:

Global Participation: Engage from any location worldwide, facilitated by our seamless collaboration with Foundance.org, known for its robust digital hackathon platform. Generous Bounties: Compete for prizes worth $6000 as you bring your innovative solutions to life, generously sponsored by our partners committed to advancing the web3 ecosystem. Expert Guidance: Receive unparalleled support and feedback from industry leaders who are as passionate about decentralized solutions as you are. Our mentors are seasoned professionals from the sponsoring organizations who offer direct insights and guidance. Collaborative Environment: Work alongside peers and experts in a dynamic online setting, fostering collaboration and the exchange of revolutionary ideas.

Join Us:

Whether you're a developer seasoned in blockchain technology, an entrepreneur in the tech space, or a tech enthusiast eager to learn more about decentralized data, Hack'N Heights provides a perfect platform to deepen your expertise and showcase your skills."

# link to call for particioation
link = " "

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "00 EUR"

# link to the registration or ticket purchase page
link = "https://app.foundance.org/events/hacknheights?tab=overview"

# custom action button label
#button = "Join Us!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://app.foundance.org/events/hacknheights?tab=overview"

# twitter account
twitter = " "

# public matrix channel
matrix = " "

# public telegram group
telegram = " "

# docs
#docs = " "

# discord
discord = "https://discord.com/invite/9BzMm9qp3S"
```
