### ISSUE TITLE
Friends With Benefits: "CEREMONY"

### ISSUE THREAD

**Issue by enaranazarova** [blockchainweek/data#63]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "CEREMONY by FWB"

# shortest possible name (without year)
shortname = "CEREMONY"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["party"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Friends With Benefits"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "enaranazarova"

# A point of contact (responsible person)
poc = "Enara Nazarova"

# the start date of the event
date = "2024-05-25"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00-23:59"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["Monopol, Provinzstraße 40-44, 13409 Berlin, https://monopol-berlin.com"]

# the event venue name
venueName = "Monopol"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/node/9774919599"

# the event venue address
venueAddress = "Provinzstraße 40-44, 13409 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 200

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [""]

# tags for the event, will show up as labels.
# pick 1-4
tags = [""]

# A logo attachment
logo = "
![FWB Square](https://github.com/blockchainweek/data/assets/16925391/17c546c2-7ee2-4c1a-a5cd-65bfdb8348d1)
"

# a description of the event.
description = """
Dear Berliner,

We're thrilled to invite you to the 4th edition of "CEREMONY," a unique fusion of spirituality and digital innovation celebrating Berlin's culture. Join us at the iconic Monopol for a theatrical experience with a hint of irreverence guided by Lori Baldwin and talents from Tresor and Lunacy.

May 25th at 9pm. Doors close at 10pm sharp.

Space is extremely limited, so please secure your ticket early and keep an eye out for a confirmation email containing event details. 

We look forward to welcoming you!

FWB Berlin
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/ceremony"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "25 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/ceremony"

# custom action button label
#button = "Buy tickets!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://fwb.help/"

# twitter account
twitter = "https://twitter.com/FWBtweets"

# public matrix channel
matrix = ""

# public telegram group
telegram = ""

# docs
#docs = ""

# discord
discord = ""
```
