### ISSUE TITLE
[NEW]: zk Späti with zkSync & crypto girls club

### ISSUE THREAD

**Issue by cryptogirlsclubberlin** [blockchainweek/data#69]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "zk Späti with zkSync & crypto girls club"

# shortest possible name (without year)
shortname = "The zk Späti"


# type of the event
#  available types (you can choose more):
#   * meetup
#   * party
#   * other
types = ["meetup, party"]

# status of the event
#  available types:
#   * published
status = "published"

# the name of the group organizing the event
org = "zkSync, crypto girls club"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "cryptogirlsclubberlin"

# A point of contact (responsible person)
poc = "Zoe Faircloth"

# the start date of the event
date = "2024-05-22"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-21:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "NEST Schank- und Speisewirtschaft"

# link to the venue on open-street maps
venueUrl = "https://www.openstreetmap.org/node/1248728521"

# the event venue address
venueAddress = "[Görlitzer Str. 52, 10997 Berlin](https://www.google.com/maps/place//data=!4m2!3m1!1s0x47a84e4d15dd5631:0x86b65817acef8820?sa=X&ved=1t:8290&ictx=111)"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 300

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [""]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["devrel", "cryptography" "rollups" "account abstraction" "l2s"]

# A logo attachment
logo = "[logo.png](https://ibb.co/qp1nmcZ)"

# a description of the event.
description = """
Step into The BlockSpäti and prepare to enter a new reality where your favourite crypto brand is available to drink over the counter. Join us from day to dusk for Berlin Blockchain Week at our authentic Berlin experience: a two-floor mini-mart.

We'll be diving into account abstraction, quantum cryptography and cross-chain compatibility with a lineup so hard even Berghain couldn't curate.

PANEL - 3:30PM

Hira Siddiqui - CEO & Co-Founder, Plurality Network
Lana Ivina - Blockchain Developer, Starkware
Albiona Hoti - DevRel, Matter Labs
Bianca Buzea - Head of Devrel, LUKSO

​PRESENTATIONS - 4:20PM

"Quantum Cryptography: Does It Have a Future?"
Olena-Ivanna Oshchypok Applied Cryptographer Engineer at Matter Labs

"Account abstraction: user interaction and experience"
Albiona Hoti - DevRel, Matter Labs

​AFTER HOURS - 6PM

Join us for afterhours for sassy-named cocktails, free flowing food and drink, killer merch in the merch mart and live music and a DJ set by ohr collective afterwards till dark.

Acoustic Nigerian set by [Dammy Daas]
DJ set by [Ohr]
"""

[cfp]
# link to call for particioation
link = "https://example.com/speaker"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/zkspati"

# custom action button label
#button = "Secure your spot"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/zkspati"

# twitter account
twitter = "https://twitter.com/zksync"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
discord = "https://discord.com/invite/AsDf1337"
```
