### ISSUE TITLE
[NEW]: PERMA 📸 Closed Beta (Berlin, Germany)

### ISSUE THREAD

**Issue by khawrk** [blockchainweek/data#70]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "PERMA 📸 Closed Beta (Berlin, Germany)"

# shortest possible name (without year)
shortname = "PERMA 📸 "

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Future Primitive"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "khawrk"

# A point of contact (responsible person)
poc = "Benny Giang"

# the start date of the event
date = "2024-05-24"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "12:00-3:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "La Fève"

# link to the venue on open-street maps
venueUrl = "https://www.google.co.uk/maps/place/La+F%C3%A8ve/@52.493545,13.4461651,16.78z/data=!3m1!5s0x47a84fab99bb8db9:0x1fc31ee4911c7670!4m15!1m8!3m7!1s0x47a84fe5ca73aa59:0x55017540a77804d3!2zTGEgRsOodmU!8m2!3d52.4911958!4d13.4477001!10e5!16s%2Fg%2F11sbj0c4fj!3m5!1s0x47a84fe5ca73aa59:0x55017540a77804d3!8m2!3d52.4911958!4d13.4477001!16s%2Fg%2F11sbj0c4fj?entry=ttu"

# the event venue address
venueAddress = "Karl-Kunger-Straße 58, 12435 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 20

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum", "base"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["PERMA", "NFT", "photography", "art"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
Come hang out with PERMA team at La Fève and get access to our PERMA Closed Beta, the first time launched in Berlin.
"""

[cfp]
# link to call for particioation
link = "https://partiful.com/e/f0IkFMI5L0PT3GTY0CYn"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0"

# link to the registration or ticket purchase page
link = "https://partiful.com/e/f0IkFMI5L0PT3GTY0CYn"

# custom action button label
#button = "RSVP Now!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://partiful.com/e/f0IkFMI5L0PT3GTY0CYn"

# twitter account
twitter = "https://twitter.com/perma_net"


```
