### ISSUE TITLE
AI Agents: Value Synergies of Blockchain and AI - Supporting Builders from A to Z

### ISSUE THREAD

**Issue by GutscheRC** [blockchainweek/data#73]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "AI Agents: value synergies of blockchain and AI - Supporting Builders from A to Z"

# shortest possible name (without year)
shortname = "Value Synergies of Blockchain and AI"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Crypto Invest Berlin"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "GutscheRC"

# A point of contact (responsible person)
poc = "Rapha"

# the start date of the event
date = "2024-05-20"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "17:30-21:30"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["lisk-centre"]

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 150

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = 

# tags for the event, will show up as labels.
# pick 1-4
tags = ["aiagents", "blockchain", "web3"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
​We're thrilled to kick off this year's Berlin Blockchain Week with an event where the convergence of artificial intelligence and blockchain technology takes center stage. This intersection has emerged as one of the most dynamic and promising sectors in our industry.

​Our focus is on exploring the tangible value offered by live products at this intersection. The presenting projects will offer the audience practical insights into live AI agents and the benefits they bring.

​We aim to move beyond the buzz and highlight real applications and live agents demoed by their builders. Join us to glean insights from the brightest and most innovative projects in this exciting industry.
"""

[cfp]
# link to call for particioation
link = "https://lu.ma/phurgmbn"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = 

# link to the registration or ticket purchase page
link = 

# custom action button label
#button = "RSVP now"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/phurgmbn"

# twitter account
twitter = "https://twitter.com/CryptoInvestBln"

# public matrix channel
matrix = 

# public telegram group
telegram = "https://t.me/+wEML3dssvSRkMTBi"

# docs
#docs = 

# discord
discord =  
```
