### ISSUE TITLE
[NEW]: Blockchain and Open Source: A Look at the Legal Landscape

### ISSUE THREAD

**Issue by curiousgeorge21** [blockchainweek/data#77]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Blockchain and Open Source: A Look at the Legal Landscape"

# shortest possible name (without year)
shortname = "Blockchain and Open Source: A Look at the Legal Landscape"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["other-breakfast"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "JUST Open Source Stiftung", "YPOG", "The Blockchain Lawyers Forum", "EUCI (European Crypto Initiative)"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "curiousgeorge21"

# A point of contact (responsible person)
poc = "Lex Gillon"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00-11:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = [""]

# the event venue name
venueName = "Blumental"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=2760829009&class=amenity"

# the event venue address
venueAddress = "Engeldamm 64, 10179 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 60

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [""]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["legal", "open source software"]

# A logo attachment
logo = "<img width="794" alt="Screenshot 2024-05-14 at 17 26 56" src="https://github.com/blockchainweek/data/assets/36596158/e382c99f-fc8c-4eec-bb5a-1bcc3db314ff">"

# a description of the event.
description = """
​Come join us for breakfast and a engaging discussion with the legal folks in Web3.

​Agenda:

​9AM: Doors Open, Breakfast Served

​9:30AM: Panel Starts

​Post Panel: Networking

​This discussion sits at the intersection between blockchain and open source. Our panelists will look at how the existing and upcoming regulatory frameworks affect the creation and use of blockchain solutions built on open-source software. Additionally, we will discuss how regulations such as the Data Act, Markets in Crypto-Assets Regulation, the Cyber Resilience Act and Product Liability Directive impact open-source solution development, the open-source community, and the future of blockchain innovation. We will also look at the challenges and opportunities in this area, offering practical advice for developers and companies to grow and stay compliant.

​This event is brought to you by JUST Open Source Stiftung, YPOG, The Blockchain Lawyers Forum, and EUCI (European Crypto Initiative), and World of Women.

Our Panelists:

​[Benedikt Flöter](https://www.linkedin.com/in/benedikt-floeter/) (YPOG)

​[Marina Markezic ](https://www.linkedin.com/in/marinamarkezic/) (European Crypto Initiative)

​[Joanna Rindell ](https://www.linkedin.com/in/joanna-rindell/)(Moderator, World of Women)
"""



[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/cy8jbq96"

# custom action button label
#button = "Register!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

```
