### ISSUE TITLE
[NEW]: ZK meetup: education of zk with Least Authority, Polygon, TU Berlin and ZK Hack 

### ISSUE THREAD

**Issue by alv-around** [blockchainweek/data#8]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "ZK Hack Meetup – ZK Education: How Do We Learn ZK? with Least Authority, Polygon, TU Berlin & ZK Hack "

# shortest possible name (without year)
shortname = "ZK Hack Meetup"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Least Authority, Polygon, TU Berlin and ZK Hack "

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "alvaro-alonso"

# A point of contact (responsible person)
poc = "Alvaro Alonso"

# the start date of the event
date = "2024-05-21"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "18:00-21:30"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "TU Berlin, EINS - Innovationsplattform und Coworkingspace"

# link to the venue on google maps
venueUrl = "https://maps.app.goo.gl/yh1fRbZaudbNBJQs6"

# the event venue address
venueAddress = "Ernst-Reuter-Platz 1, 10587 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 100

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = []

# tags for the event, will show up as labels.
# pick 1-4
tags = ["zero-knowledge", "cryptography", "education"]

# A logo attachment
logo = "zk_hack_meetup_berlin_visual_v2.png"

# a description of the event.
description = """
Whether you’re a longstanding member of the ZK Hack community, or just curious about zero-knowledge technology, join us on Tuesday May 21st at 18:00 in Berlin! 

This 4th ZK Hack Meetup is produced in partnership with Least Authority, Polygon and Technische Universität Berlin. 

It's the opportunity to meet fellow ZK and privacy enthusiasts, listen to our speakers talking about how to learn ZK, and have a good time!
"""

[cfp]
# link to call for participation
link = "https://lu.ma/zk-hack-meetup-berlin"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/zk-hack-meetup-berlin"

# custom action button label
#button = "RSVP!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/zk-hack-meetup-berlin"

# twitter account
twitter = "https://twitter.com/__zkhack__"

# public matrix channel
matrix = ""

# public telegram group
telegram = "https://t.me/+TORo7aknkYNLHmCM"

# docs
#docs = ""

# discord
discord = "https://discord.gg/YdrpFtzGut"
```
