### ISSUE TITLE
[NEW]: Breadchain Launch Event at Moos Space

### ISSUE THREAD

**Issue by tbsoc** [blockchainweek/data#80]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Breadchain Launch Event at Moos Space"

# shortest possible name (without year)
shortname = "Breadchain Launch Event"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["conference"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Breadchain Cooperative"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "tbsoc"

# A point of contact (responsible person)
poc = "Joshua Davila"

# the start date of the event
date = "2024-05-25"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00-20:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["MOOS Space"]

# the event venue name
venueName = "Moos Space"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/search.html?q=moos+space"

# the event venue address
venueAddress = "MOOS Space, Moosdorfstraße 7-9, Plänterwald, Treptow-Köpenick, Berlin, 12435"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 200

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["ethereum"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["solarpunk", "ethereum", "gnosis chain", "solidarity"]

# A logo attachment
logo = "
![berlin launch side event](https://github.com/blockchainweek/data/assets/80857213/942ad0f4-7891-4231-ade5-fbcfa97ccdcf)
"

# a description of the event.
description = """
Join us during Berlin Blockchain Week for the Breadchain Launch Event at the Moos Space in Berlin on May 25th! During the event we will be showcasing the work we've been doing at Breadchain Cooperative for building the infrastructure for a post-capitalist web3. [Breadchain Cooperative](https://breadchain.xyz/) is a cooperative network of blockchain projects working to advance a progressive vision for the technology and its effect on society by scaling solidarity through our BREAD community token and other [solidarity primitives](https://breadchain.mirror.xyz/nwQx4CqPAcwZ5zSNB2_K25N1quOF1NGcKaYcS3S33CA). The primary infrastructure being built at Breadchain is to ask ourselves what if progressives had their own community currency and credit union? Where would we decide to put resources towards to build a post-capitalist political economy?

 The other members of Breadchain include the [Crypto Commons Association](https://crypto-commons.org/), [Symbiota Coop](https://symbiota.coop/) (which includes the Dandelion events platform you're looking at now), and Labor DAO. 

The series of events that will take place for the full event include 

1) a ~[real hands on sourdough bread baking workshop](https://www.eventbrite.de/e/sourdough-bread-workshop-tickets-903864481997)~ led by Edible Alchemy, the bakery at Moos, to give a chance to people who work on their computers all day to work with their hands and meet with other solidarity loving folks  (limited availability so please purchase tickets beforehand)

2) presentations from Breadchain Cooperative members and associated projects building out technology for scaling solidarity with BREAD

3) onboarding  sessions for people who believe in the cause but maybe don't yet have any crypto and 

4) a [gift economy solidarity dinner at Moos](https://dandelion.events/e/s4ngq) with  the artist Mirna Bamieh from the Palestinian Hosting Society to wind it all down 🎉(limited availability so please sign up ahead of time)

There will be food (including the bread baked in the workshop) and refreshments available throughout to be purchased with BREAD. You will be able to get BREAD with cash at the event, so no worries if you don't have any tokens yet. In preparation however, we recommend that you download the [Citizen Wallet](https://citizenwallet.xyz/) app which will be used to make purchases during the event. By creating and using the BREAD token helps fund the cooperative and also gives you the ability to vote on how the yield generated from it among the various projects part of the cooperative. You can bake some BREAD on the [Bread Crowdstaking Application](https://app.breadchain.xyz/) on Gnosis Chain with xDai.
"""

[cfp]
# link to call for particioation
link = "https://dandelion.events/e/y3xkf"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "tickets"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://dandelion.events/e/y3xkf"

# custom action button label
#button = "Register to attend!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://dandelion.events/e/y3xkf"

# twitter account
twitter = "https://twitter.com/breadchain_"

# discord
discord = "https://discord.gg/ChDeH5GRth"
```
