### ISSUE TITLE
[NEW]:  Celestia Light Run Event

### ISSUE THREAD

**Issue by natn3t** [blockchainweek/data#83]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Celestia Light Run"

# shortest possible name (without year)
shortname = "Celestia Light"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["other"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Celestia Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "devnatnet"

# A point of contact (responsible person)
poc = "Natnet"

# the start date of the event
date = "2024-05-23"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:15-11:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "Moltke Monument"

# link to the venue on open-street maps
venueUrl = "https://lu.ma/cldspsln"

# the event venue address
venueAddress = "Spreeweg 1, 10557 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 30

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["celestia"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["running", "modularity", "breakfast"]

# A logo attachment
logo = "https://github.com/blockchainweek/data/assets/115193410/1cc45099-e5fc-4bc0-a2a1-372608f2467f"

# a description of the event.
description = """
Join the Celestia team for a morning jog, covering 5.5-6km at a slow pace. We'll run from the Siegessäule along the river, through Monbijoupark and end our run with our final coffee and pastries!
"""

[cfp]
# link to call for particioation
link = ""

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "invites"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/cldspsln"

# custom action button label
#button = "Sign Up"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/cldspsln"

# twitter account
twitter = ""

# public matrix channel
matrix = ""

# public telegram group
telegram = ""

# docs
#docs = ""

# discord
discord = ""
```
![Celestia_Light_Run2](https://github.com/blockchainweek/data/assets/115193410/1cc45099-e5fc-4bc0-a2a1-372608f2467f)
