### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by cryptogirlsclubberlin** [blockchainweek/data#84]
Please add a new event

```toml
# the name of your event
name = "Subsquid & Fuel Tech Brunch"

# shortest possible name (without year)
shortname = "Subsquid & Fuel Tech Brunch"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Subsquid & Fuel Tech Brunch"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "Subsquid"

# A point of contact (responsible person)
poc = "Roman Kemper"

# the start date of the event
date = "2024-05-15"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00-1:00pm"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "NEST Schank- und Speisewirtschaft
"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/search.html?q=G%C3%B6rlitzer+Str.+52%2C+10997+Berlin"

# the event venue address
venueAddress = "Görlitzer Str. 52, 10997 Berlin"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 80

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = [ "polkadot"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["subsquid, "decentralization" "L2"]

# A logo attachment
logo = "[logo.png](https://ibb.co/f2bf05H)"

# a description of the event.
description = """
​GM cryptopunks and decentralization enjoyooors.

We're already a few days through blockchain week... it's probably time for a refuel!

Join us for a reset with us, at the Fuel x Subsquid Tech Brunch.

Why join?
- There will be croissants & breakfast buffet
- Plenty of liquidity, including Club Mate, the go-to drink for real Berliners, or those aspiring to be
- Crypto dev insights straight from the source

​Talk by [David Mihal](https://twitter.com/dmihal), Senior Architect @ Fuel

Light-contracts - Understanding Fuel's Predicates
The Fuel L2 features a new primitive, known as "predicates". Learn how predicates differ from "smart contracts", and how to use them to build account-abstraction wallets, DeFi apps, and more!

Sounds good? Then sign up and see you soon.
"""

[cfp]
# link to call for particioation
link = "https://example.com/speaker"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0 EUR"

# link to the registration or ticket purchase page
link = "https://lu.ma/q7kr9if2"

# custom action button label
#button = "Reserve your spot!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/q7kr9if2/"

# twitter account
twitter = "https://twitter.com/subsquid"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
discord = "https://discord.com/invite/AsDf1337"
```
