### ISSUE TITLE
[NEW]:  Open Data Brunch with Subsquid

### ISSUE THREAD

**Issue by cryptogirlsclubberlin** [blockchainweek/data#86]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
# the name of your event
name = "Open Data Brunch with Subsquid"

# shortest possible name (without year)
shortname = "Open Data Brunch with Subsquid"

# type of the event
#  available types (you can choose more):
#   * meetup
#   * conference
#   * hackathon
#   * expo
#   * party
#   * other
types = ["meetup" "brunch"]

# status of the event
#  available types:
#   * idea
#   * planning
#   * published
status = "published"

# the name of the group organizing the event
org = "Subsquid"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with #bbw24 organizers)
dri = "Subsquid"

# A point of contact (responsible person)
poc = 'Roman K"

# the start date of the event
date = "2024-05-16"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00-13:00"

# Link to venues from the Places table - use this OR enter venueName, venueUrl and venueAddress
# venues = ["gabriel-loci"]

# the event venue name
venueName = "NEST Schank- und Speisewirtschaft
"

# link to the venue on open-street maps
venueUrl = "https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=1248728521&class=amenity"

# the event venue address
venueAddress = "52, Görlitzer Straße, Luisenstadt, Kreuzberg, Friedrichshain-Kreuzberg, Berlin, 10997, Germany"

# the languages in which the event will take place (you can choose more)
languages = ["english"]

# the max number of attendees of the event
attendees = 100

# blockchains that the event deals with
# if it is an interchain event, then leave blank
chains = ["polkadot"]

# tags for the event, will show up as labels.
# pick 1-4
tags = ["sdata", "cryptography"]

# A logo attachment
logo = "logo.png"

# a description of the event.
description = """
Dive into open data and start your Thursday at the Blockspäti!

​The Subsquid team invites you to a lavish brunch followed by games and casual networking to start the day on the right foot.

​Don't miss this mixer if you appreciate:

​Brunch with all the fixings

​Open data

​Different games and activities

​Your hosts at Subsquid
​​Subsquid Network is Web3 necessiware—a decentralized data lake and query engine for blazing-fast cross-chain indexing and queries. Infinitely horizontally scalable, Subsquid makes the consumer dApps that real people want to use possible, from social media to games and DeFi. Secured by ZK proofs, Subsquid supports over 100 networks. Learn more: https://subsquid.io/
"""

[cfp]
# link to call for particioation
link = "https://example.com/speaker"

[registration]
# type of registration
#  Possible values:
#   * tickets
#   * invites
#   * signup
type = "signup"

# price of the ticket
price = "0"

# link to the registration or ticket purchase page
link = "https://lu.ma/ifha7ucq"

# custom action button label
#button = "Sign up!"

# status of registrations
#  Possible values:
#   * available
#   * sold-out
#   * closed
status = "available"

[links]
# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
web = "https://lu.ma/ifha7ucq"

# twitter account
twitter = "https://twitter.com/subsquid"

# public matrix channel
matrix = "https://matrix.to/#/!example:example.org"

# public telegram group
telegram = "https://t.me/example"

# docs
#docs = "https://example.org/docs"

# discord
discord = "https://discord.com/invite/AsDf1337"
```
